# Wards Main configuration. Version ${projectVersion}
# Created by Divios
# =========================================================
# Fields Explanation:
#   <prefix>:
#       - Prefix to display with every message of this plugin.
# ============================
#   <debug>:
#       - Don't enable it, only useful if the developer asks for it
# ============================
#   <default-buy-price>:
#       - Default buy price for newly created items.
# ============================
#   <default-sell-price>:
#       - Default sell price for newly created items.
#   <default_timer>:
#       - Default timer assigned to newly created shops.
# ============================
# ============================
#   <vault-currency-name>:
#       - Change the name of vault currency when displayed.
# ============================
#   <integer-bal>
#        - If false, round prices like 20.0 would be displayed as 20, if true: 20.0
# ============================
#   <econ-names>
#        - Option to override the displayed economy names
# ============================
# You must restart for changes to take effect when editing this file!
# =========================================================
settings:
  prefix: "&e&lDailyShop &7> "
  debug: false
  default-buy-price: 500.0
  default-sell-price: 20
  default_timer: 86400
  vault_name: "&7Vault"
  integer-bal: true
  econ-names:
    economy_name_to_change: "Custom economy name"

